# Generated by Django 4.2.1 on 2024-05-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital_support.department",
            ),
        ),
    ]
