# Generated by Django 4.2.1 on 2024-05-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_support", "0002_alter_doctor_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="contact_details",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="contact_details",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="contact_details",
            field=models.CharField(max_length=10),
        ),
    ]
