# Generated by Django 4.2.1 on 2024-05-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_support", "0003_alter_doctor_contact_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("user_email", models.EmailField(max_length=254)),
            ],
        ),
    ]
